apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krishnapuppala20/backend:lat
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb:27017"
            - name: DATABASE_NAME
              value: "ead_ca2"
            - name: DATABASE_COLLECTION
              value: "ead_2024"