apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krishnapuppala20/frontend:lat
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
          ports:
            - containerPort: 22137
          env:
            - name: WEBSERVICE_HOST
              value: "backend"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
