name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Docker login
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      # Build backend
      - name: Build Backend Image
        run: docker build -t krishnapuppala20/backend:lat ./BACK_END

      # Build frontend
      - name: Build Frontend Image
        run: docker build -t krishnapuppala20/frontend:lat ./FRONT_END

      # Push images
      - name: Push Backend
        run: docker push krishnapuppala20/backend:lat

      - name: Push Frontend
        run: docker push krishnapuppala20/frontend:lat

      # Verify cluster
      - name: Check Kubernetes
        run: kubectl get nodes
      - name: Clean Kubernetes Resources
        run: |
            kubectl delete -f k8s/ --ignore-not-found=true

      # Terraform
      - name: Terraform Init
        run: terraform init

      
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Install monitoring 
      - name: Add Helm Repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Install Monitoring Stack
        run: helm upgrade --install monitoring prometheus-community/kube-prometheus-stack --set grafana.adminPassword=admin123 --set grafana.service.type=NodePort --set grafana.service.nodePort=30000 --set prometheus.service.type=NodePort --set prometheus.service.nodePort=30001


      - name: Check Backend Deployment
        run: kubectl rollout status deployment/backend --timeout=60s

      - name: Check Frontend Deployment
        run: kubectl rollout status deployment/frontend --timeout=60s


      - name: Backend Logs
        run: kubectl logs -l app=backend --tail=20

      - name: Frontend Logs
        run: kubectl logs -l app=frontend --tail=20


      - name: Get Minikube IP
        run: minikube ip


      - name: Show Monitoring Access
        run: |
          echo "========== MONITORING =========="
          echo "Grafana: http://$(minikube ip):30000"
          echo "Username: admin"
          echo "Password: admin123"
          echo ""
          echo "Prometheus: http://$(minikube ip):30001"
          echo "================================"

      - name: Check Pods
        run: kubectl get pods